services:
  - type: web
    name: image-search
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: NAVER_CLIENT_ID
        sync: false
      - key: NAVER_CLIENT_SECRET
        sync: false
